name: E2e Regression

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '00 23 * * *'

  workflow_dispatch:

env:
  TARGET: "%regex[.*Tests.*],com.automationexercise.tests.**.**,com.automationexercise.tests.**"

jobs:
  Edge_Linux_Test:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.14

      - name: Prepare Download Directory
        run: mkdir -p src/test/resources/downloads

      - name: Running Tests
        run: mvn clean test -Dtest="${TARGET}" -DexecutionType="LocalHeadless"

      - name: Show Single File Report
        if: always()
        run: |
          ls -la test-output/reports || true

      - name: Upload Single File Allure Report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Edge_Linux_Single_File_Report
          path: test-output/reports/*.html
          if-no-files-found: warn

  Edge_Windows_Test:
    runs-on: windows-latest

    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.14

      - name: Prepare Download Directory
        shell: powershell
        run: New-Item -ItemType Directory -Force -Path src/test/resources/downloads

      - name: Running Tests
        shell: powershell
        run: mvn clean test -Dtest="${env:TARGET}" -DexecutionType="LocalHeadless"

      - name: Show Single File Report
        if: always()
        shell: powershell
        run: |
          Get-ChildItem -Path test-output/reports -File -ErrorAction SilentlyContinue

      - name: Upload Single File Allure Report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Edge_Windows_Single_File_Report
          path: test-output/reports/*.html
          if-no-files-found: warn